#!/usr/bin/env python3
"""
Interactive setup for meetergo-mcp.

Prompts you for your meetergo token (and optional settings), then:
  1. writes a local, gitignored `.env`, and
  2. generates a ready-to-paste Claude Desktop config block — and can merge it
     into your Claude config for you (with a backup).

Security note: your token is written ONLY to `.env` and (optionally) your local
Claude Desktop config. It is NEVER written into the source code — hardcoding a
secret into a public repo would leak it. `.env` is gitignored.

Run:  python3 configure.py
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from datetime import datetime
from getpass import getpass
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent
SERVER_PATH = REPO_DIR / "meetergo_mcp.py"
ENV_PATH = REPO_DIR / ".env"
DEFAULT_BASE = "https://api.meetergo.com/v4"
DEFAULT_TIMEOUT = "30"
SERVER_KEY = "meetergo"


def prompt(label: str, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default and not secret else ""
    reader = getpass if secret else input
    try:
        value = reader(f"{label}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\nCancelled.")
        sys.exit(1)
    return value or default


def confirm(label: str, default_yes: bool = True) -> bool:
    hint = "Y/n" if default_yes else "y/N"
    ans = input(f"{label} [{hint}]: ").strip().lower()
    if not ans:
        return default_yes
    return ans in ("y", "yes")


def claude_config_path() -> Path:
    """Best-effort location of Claude Desktop's config file per-OS."""
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Claude" / "claude_desktop_config.json"
    if os.name == "nt":
        base = os.environ.get("APPDATA", str(Path.home()))
        return Path(base) / "Claude" / "claude_desktop_config.json"
    # Linux / other
    return Path.home() / ".config" / "Claude" / "claude_desktop_config.json"


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# Generated by configure.py — DO NOT COMMIT (this file is gitignored).",
        f"MEETERGO_API_KEY={values['MEETERGO_API_KEY']}",
    ]
    if values.get("MEETERGO_USER_ID"):
        lines.append(f"MEETERGO_USER_ID={values['MEETERGO_USER_ID']}")
    if values.get("MEETERGO_API_BASE") and values["MEETERGO_API_BASE"] != DEFAULT_BASE:
        lines.append(f"MEETERGO_API_BASE={values['MEETERGO_API_BASE']}")
    if values.get("MEETERGO_TIMEOUT") and values["MEETERGO_TIMEOUT"] != DEFAULT_TIMEOUT:
        lines.append(f"MEETERGO_TIMEOUT={values['MEETERGO_TIMEOUT']}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(ENV_PATH, 0o600)  # owner read/write only
    except OSError:
        pass
    print(f"✓ Wrote {ENV_PATH} (permissions 600, gitignored).")


def build_server_entry(values: dict[str, str]) -> dict:
    env: dict[str, str] = {"MEETERGO_API_KEY": values["MEETERGO_API_KEY"]}
    for key in ("MEETERGO_USER_ID", "MEETERGO_API_BASE", "MEETERGO_TIMEOUT"):
        if values.get(key):
            env[key] = values[key]
    return {
        "command": sys.executable,  # the interpreter running this script
        "args": [str(SERVER_PATH)],
        "env": env,
    }


def redacted(entry: dict) -> str:
    clone = json.loads(json.dumps(entry))
    if "MEETERGO_API_KEY" in clone.get("env", {}):
        clone["env"]["MEETERGO_API_KEY"] = "***REDACTED***"
    return json.dumps({"mcpServers": {SERVER_KEY: clone}}, indent=2)


def merge_into_claude(entry: dict) -> None:
    cfg_path = claude_config_path()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)

    config: dict = {}
    if cfg_path.exists():
        try:
            config = json.loads(cfg_path.read_text(encoding="utf-8") or "{}")
        except json.JSONDecodeError:
            print(f"! {cfg_path} exists but isn't valid JSON. Not touching it.")
            print("  Paste the block above manually instead.")
            return
        backup = cfg_path.with_suffix(f".backup-{datetime.now():%Y%m%d-%H%M%S}.json")
        shutil.copy2(cfg_path, backup)
        print(f"✓ Backed up existing config to {backup}")

    config.setdefault("mcpServers", {})
    existed = SERVER_KEY in config["mcpServers"]
    config["mcpServers"][SERVER_KEY] = entry
    cfg_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    verb = "Updated" if existed else "Added"
    print(f"✓ {verb} the '{SERVER_KEY}' server in {cfg_path}")
    print("  Restart Claude Desktop fully for it to take effect.")


def main() -> None:
    print("meetergo-mcp — guided setup\n" + "=" * 30)

    if not SERVER_PATH.exists():
        print(f"! Can't find {SERVER_PATH}. Run this from inside the repo.")
        sys.exit(1)

    print(
        "\nPaste your meetergo token. A Personal Access Token ('rgo-...') is\n"
        "recommended for automating your own workspace. Input is hidden.\n"
    )
    api_key = prompt("MEETERGO_API_KEY", secret=True)
    while not api_key:
        print("A token is required.")
        api_key = prompt("MEETERGO_API_KEY", secret=True)

    user_id = ""
    if api_key.startswith("ak_live") and confirm(
        "That looks like a Platform API Key. Set a MEETERGO_USER_ID to act as a user?",
        default_yes=False,
    ):
        user_id = prompt("MEETERGO_USER_ID")

    api_base = prompt("MEETERGO_API_BASE", default=DEFAULT_BASE)
    timeout = prompt("MEETERGO_TIMEOUT (seconds)", default=DEFAULT_TIMEOUT)

    values = {
        "MEETERGO_API_KEY": api_key,
        "MEETERGO_USER_ID": user_id,
        "MEETERGO_API_BASE": api_base,
        "MEETERGO_TIMEOUT": timeout,
    }

    print()
    write_env(values)

    entry = build_server_entry(values)
    print("\nClaude Desktop config block (token redacted for display):\n")
    print(redacted(entry))
    print()

    if confirm(f"Install this into your Claude Desktop config at\n  {claude_config_path()} ?"):
        merge_into_claude(entry)
    else:
        print("Skipped. Paste the block above into your Claude config yourself")
        print("(with the real token from your .env).")

    print("\nDone. Tip: run `mcp dev meetergo_mcp.py` and call get_me to test auth.")


if __name__ == "__main__":
    main()
